### PR TITLE
pr#10 with slight changes

### PR DESCRIPTION
**Pull request by sgreben**
This is the commits from #10 plus another refactoring commit + README update (I can't push to the other PR's source branch ;)). @dawidmalina does this suit you as well?

### CODE REVIEW

**Comment by dawidmalina** [comment]
LGTM

**Comment by sgreben** [comment]
Could you cherry-pick these two into your branch? Then we do the change as part of your PR (and just close this one) :)

**Comment by dawidmalina** [comment]
@sgreben cherry-pick is done as you requested.

**Comment by sgreben** [comment]
Cool, thanks! I merged #10 now.

**Pull request closed without merging**
